In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# **DATASET**

In [2]:
df = pd.read_csv('../../data/pima-indians-diabetes.csv')
df.head()

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

# **PHÂN TÍCH DỮ LIỆU (EDA)**

## Tổng quan dữ liệu

In [3]:
row, column = df.shape
print(f"Row: {row}, Column: {column}")

Row: 767, Column: 9

In [4]:
# Gán lại tên cột chuẩn
df.columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

In [5]:
# Thông tin kiểu dữ liệu, null
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               767 non-null    int64
 1   Glucose                   767 non-null    int64
 2   BloodPressure             767 non-null    int64
 3   SkinThickness             767 non-null    int64
 4   Insulin                   767 non-null    int64
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64
 8   Outcome                   767 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
# Kiểm tra giá trị thiếu (null)
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
# Thống kê cơ bản các cột số
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000
mean,3.842243,120.859192,69.101695,20.517601,79.903520,31.990482,0.471674,33.219035,0.348110
std,3.370877,31.978468,19.368155,15.954059,115.283105,7.889091,0.331497,11.752296,0.476682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,32.000000,32.000000,0.371000,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,127.500000,36.600000,0.625000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
# Kiểm tra dữ liệu có trùng lặp
df.duplicated().any()

np.False_

**Nhân xét:**

*   Kích thước dữ liệu là (767, 9).



*   Không có cột thiếu dữ liệu

*   Outcome là nhãn của dữ liệu.

*   Các cột có sự phân tán cao là: Insulin, Glucose, Age.
*   Các cột có sự phân tán trung bình là: BMI, BloodPressure.
*   Các cột có sự phân tán thấp là: Pregnancies, SkinThickness, DiabetesPedigreeFunction.

*   Dữ liệu không có sự trùng lặp.